# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

# https://www.appveyor.com/ Windows CI configuration file.

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python37"

  # To update these values, visit AppVeyor's site, click the user icon and scroll down to Encrypt Data.
  SG_SERVER_URL:
    secure: lIYAxmyz5GEvnbxqE1pAoNuU5+04RYsSzfjRxjqV7vI=
  SG_HUMAN_LOGIN: appveyor
  SG_HUMAN_NAME: App Veyor
  SG_HUMAN_PASSWORD:
    secure: 0/BofzMkXtzwtRqzC94FHt3lcyMBG0rr2w0rUropeT4=
  SG_SCRIPT_NAME: python-api-test
  SG_API_KEY:
    secure: 8bHvvT/83p+3wHyQh4qsfXP3aBENRzk0DbXosKC/cuc=
  SG_PROJECT_NAME: SG unittest project for AppVeyor

build: off

before_test:
  # The certificate store of the build machine is out of date and is missing a
  # new certificate authority used by Amazon for S3, so we need to update it.
  # See https://developer.shotgunsoftware.com/c593f0aa/
  - ps: |
      $cert_url = "https://www.amazontrust.com/repository/SFSRootCAG2.cer"
      $cert_file = New-TemporaryFile
      Invoke-WebRequest -Uri $cert_url -UseBasicParsing -OutFile $cert_file.FullName
      Import-Certificate -FilePath $cert_file.FullName -CertStoreLocation Cert:\LocalMachine\Root

test_script:
  # Put your test command here.
  # If you don't need to build C extensions on 64-bit Python 3.3 or 3.4,
  # you can remove "build.cmd" from the front of the command, as it's
  # only needed to support those cases.
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python version you want to use on PATH.
  - "tests\\run_appveyor.bat"
